export const SET_TOKEN = "SET_TOKEN";
export const RESET_TOKEN = "RESET_TOKEN";
export const GET_DIRECTORY_PENDING = "GET_DIRECTORY_PENDING";
export const GET_DIRECTORY_SUCCESS = "GET_DIRECTORY_SUCCESS";
export const GET_DIRECTORY_FAILURE = "GET_DIRECTORY_FAILURE";

export const getDirectorySet = {
    pending: GET_DIRECTORY_PENDING,
    success: GET_DIRECTORY_SUCCESS,
    failure: GET_DIRECTORY_FAILURE
};
